### ISSUE TITLE
The plug-in switch mini (TZWP-102)(313510) energy measurement stops

### ISSUE THREAD

**Issue by Turtures** [yhaugom/com.telldus#14]
The plug-in switch mini (TZWP-102)(313510) energy measurement stops working after about a week. pull it out and reconnect it will work again for some week....

**Comment by DanieLindh** [comment]
Got the same error for one of my slim plugins. It doesn’t report energy consumption, it did at start but no more.

**Comment by yhaugom** [comment]
@Turtures and @DanieLindh can you both create and send me a diagnostics report?
In the new app it is under …More - Apps - Tellus - settings - Create diagnostics report.
The old I guess it is some place under the app settings as well?

**Comment by DanieLindh** [comment]
b1a9d5cf-718c-452d-bcc3-9d904597968f
32a87985-ef72-4c4e-98f9-4acdf9f1c060

Made 2 for some reason :)

// Daniel Lindh

________________________________
Från: Yngve Haugom <notifications@github.com>
Skickat: fredag, januari 18, 2019 17:39
Till: yhaugom/com.telldus
Kopia: Daniel Lindh; Mention
Ämne: Re: [yhaugom/com.telldus] The plug-in switch mini (TZWP-102)(313510) energy measurement stops (#14)


@Turtures<https://github.com/Turtures> and @DanieLindh<https://github.com/DanieLindh> can you both create and send me a diagnostics report?
In the new app it is under …More - Apps - Tellus - settings - Create diagnostics report.
The old I guess it is some place under the app settings as well?

**Comment by yhaugom** [comment]
This doesn’t appear to be app related. Asked around on the slack developer channel, and it seems to be a problem with some core functions. I am going to close this issue since you got the meassurements first, and then it stopped working, I believe it has not to do with my part of the code. 
If however you find some evidence that it is, please feel free to reopen or comment.
I would suggest you file a report to the Athom support team. 
Here are the diagnostic report if you are interested, and maybe attach to Athom support?

`Note: this log has been manually submitted by a user.
Log ID: 32a87985-ef72-4c4e-98f9-4acdf9f1c060

---- stdout ----
2019-01-18 16:10:24 [log] [telldusApp] ${Homey.manifest.id} is running...
2019-01-18 16:10:25 [log] [ManagerDrivers] [TZWP-102] [0] ZwaveDevice has been inited
2019-01-18 16:10:25 [log] [ManagerDrivers] [TZWP-102] [1] ZwaveDevice has been inited

---- stderr ----
2019-01-18 16:10:30 [err] [ManagerDrivers] [TZWP-102] [1] { Error: request_timeout
   at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
   at JSON.parse (<anonymous>)
   at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
   at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
   at Array.map (<anonymous>)
   at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
   at emitTwo (events.js:126:13)
   at process.emit (events.js:214:7)
   at emit (internal/child_process.js:762:12)
   at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'request_timeout' }
2019-01-18 16:10:31 [err] [ManagerDrivers] [TZWP-102] [1] { Error: TRANSMIT_COMPLETE_NO_ACK
   at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
   at JSON.parse (<anonymous>)
   at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
   at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
   at Array.map (<anonymous>)
   at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
   at emitTwo (events.js:126:13)
   at process.emit (events.js:214:7)
   at emit (internal/child_process.js:762:12)
   at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'TRANSMIT_COMPLETE_NO_ACK' }
`

**Comment by Turtures** [comment]
dehumidifiers stopped measuring watts now
report sent


Med vänliga hälsningar!
Tom Danielsson
