### ISSUE TITLE
Mini plug not working in flows

### ISSUE THREAD

**Issue by Paronfesken** [yhaugom/com.telldus#22]
Works in app if switched manually

93177708-98e0-43f7-94f1-e533294b0d75

**Comment by yhaugom** [comment]
I cannot see how any error in the app is doing this. I can see something times out in the log, but that is right after init of the devices. Sorry, do not know how to fix. Could you try Athom support? I tried, but they forwarded me to Slack Developer channel, where I didn't get much help so far.

```
A crash occurred for your app (version 1.1.2) at Mar 19, 2019 8:36 PM (UTC).
Homey software version: 2.0.4
Crash report:
Note: this log has been manually submitted by a user.
Log ID: 93177708-98e0-43f7-94f1-e533294b0d75
---- stdout ----

2019-03-15 16:22:45 [log] [telldusApp] ${Homey.manifest.id} is running...
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [0] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [1] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [2] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [3] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [4] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-100] [5] ZwaveDevice has been inited
2019-03-15 16:22:46 [log] [ManagerDrivers] [TZWP-102] [0] ZwaveDevice has been inited
---- stderr ----
2019-03-15 16:23:16 [err] [ManagerDrivers] [TZWP-102] [0] { Error: timeout
at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
at JSON.parse (<anonymous>)
at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
at Array.map (<anonymous>)
at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
at emitTwo (events.js:126:13)
at process.emit (events.js:214:7)
at emit (internal/child_process.js:762:12)
at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'timeout' }
2019-03-15 16:23:16 [err] [ManagerDrivers] [TZWP-102] [0] { Error: timeout
at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
at JSON.parse (<anonymous>)
at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
at Array.map (<anonymous>)
at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
at emitTwo (events.js:126:13)
at process.emit (events.js:214:7)
at emit (internal/child_process.js:762:12)
at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'timeout' }
```
